---
title: "DVC Example"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## install
```{r}
devtools::install_github("git@github.com:insilica/dvcr.git")
library(dvcr)
```
## Adding files to track locally with dvcr
```{r}
data_dir <- here::here("data")
dir.create(data_dir)
cars_filename <- file.path(data_dir,"cars.txt")
save(cars,file=cars_filename)

# be sure to have dvc installed

# this should fail, but is left as example
dvcr::use_dvc()
dvcr::add(path=cars_filename)

```

You should also commit the data.dvc file generated
```{r}
git2r::add(path=file.path(data_dir,"cars.txt.dvc"))
```

```{r}
# this will also fail, but kept as example
dvcr::remote_add(name = "s3", url = "s3://ins-dvc/ins-dvc-example")
s3_remote = "s3"
push(remote=s3_remote)

# if this was the first time you downloaded the repo, you could do a
pull()
```

## Get files
This will place `model.pkl` into the `data` dir
```{r}
dvcr::get("https://github.com/iterative/example-get-started","model.pkl",out="data")
```

## import files
Get will only place the file into your `data` dir and will not track it
Let's track another piece of data
```{r}
dvcr::import("git@github.com:iterative/example-get-started","data/data.xml",out="data")
```

